[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
primaryColor = "#CB202D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F5"
textColor = "#1F2937"
font = "sans serif"
