"""
Recommendation output models — response contract for the recommendation pipeline.

These models represent the final output returned to the UI layer after
the LLM has ranked and explained the filtered candidates.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Recommendation:
    """
    A single ranked restaurant recommendation.

    The `explanation` field is generated by the Groq LLM and describes
    why this restaurant fits the user's preferences.
    """

    rank: int                  # 1-indexed rank position
    name: str                  # restaurant name
    cuisine: str               # joined cuisine string for display (e.g. "Italian, Continental")
    rating: float              # restaurant rating (from structured data, not LLM)
    estimated_cost: int        # cost_for_two in INR (from structured data)
    explanation: str           # Groq LLM-generated explanation of why this pick fits


@dataclass
class RecommendationMetadata:
    """
    Operational metadata for a recommendation response.

    Tracks filter statistics, Groq model used, latency, token usage,
    and whether any fallback mechanisms were activated.
    """

    candidates_considered: int          # restaurants that passed deterministic filters
    filters_applied: dict               # the actual filter values used
    model: str                          # Groq model ID (e.g. "llama-3.3-70b-versatile")
    latency_ms: float = 0.0            # wall-clock time for Groq API call
    tokens_used: int = 0               # total tokens consumed (prompt + completion)
    fallback_used: bool = False        # True if heuristic fallback was triggered
    constraints_relaxed: list[str] = field(default_factory=list)  # which filters were relaxed


@dataclass
class RecommendationResponse:
    """
    Complete response from the recommendation pipeline.

    Returned by `RecommendationService.recommend()` to the presentation layer.
    """

    summary: Optional[str]                    # Groq LLM-generated summary (may be None)
    recommendations: list[Recommendation]     # ranked list of recommendations
    metadata: RecommendationMetadata          # operational metadata for logging/debugging
